<a href="https://colab.research.google.com/github/shikejianalan/Learning-Note/blob/main/IntroToMLCW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Step 1: Importing data

In [32]:
# importing data from files

clean_data = np.loadtxt('clean_dataset.txt')
noisy_data = np.loadtxt('noisy_dataset.txt')
# for testing purpose
#print(clean_data)
#print(noisy_data)
print(noisy_data.shape)
#print(clean_data[:,7],clean_data[:,7].shape)


(2000, 8)
(7, 2000)
55
[-64. -68. -63. ... -62. -62. -59.]


In [36]:
# This cell is for test purpose
print(clean_data.T[:-1].shape)
x = list(set(clean_data.T[0]))
print(len(x),x)
print(clean_data.T[0])

(7, 2000)
55 [-74.0, -73.0, -72.0, -71.0, -70.0, -69.0, -68.0, -67.0, -66.0, -65.0, -64.0, -63.0, -62.0, -61.0, -60.0, -59.0, -58.0, -57.0, -56.0, -55.0, -54.0, -53.0, -52.0, -51.0, -50.0, -49.0, -48.0, -47.0, -46.0, -45.0, -44.0, -43.0, -42.0, -41.0, -40.0, -39.0, -38.0, -37.0, -36.0, -35.0, -34.0, -27.0, -26.0, -21.0, -20.0, -19.0, -18.0, -17.0, -16.0, -15.0, -14.0, -13.0, -12.0, -11.0, -10.0]
[-64. -68. -63. ... -62. -62. -59.]


# Step 2: Creating Decision Trees

In [17]:
# this part in the notebook calculates the information gain from entropy and reamainder after made the decision

def gain(s_all,s_left,s_right):
  '''
  This function calculates the information gain
  '''
  entropy(s_all) - remainder(s_left,s_right) 

def entropy(dataset):
  '''
  This function calculates the entropy of the dataset
  '''
  if len(dataset) > 0:
    labels = dataset[:,-1]
    unique, count = np.unique(labels, return_counts=True)
    # print(unique,count)
    p = [number/len(labels) for number in count]
    # print(p)

    result = - np.dot(p,np.log2(p))
    return result


def remainder(s_left, s_right):
  '''
  This function calculate the remainder after made the decision
  '''

  result = entropy(s_left) * len(s_left)/(len(s_left)+len(s_right)) + entropy(s_right) * len(s_right)/(len(s_left)+len(s_right))
  return result

In [18]:
entropy(clean_data)

[1. 2. 3. 4.] [500 500 500 500]
[0.25, 0.25, 0.25, 0.25]


2.0

In [3]:
def decision_tree_learning(training_dataset, depth):
  
  pass

In [23]:
def find_split(dataset):
  '''
  This function finds the split that will generate the highest information gain

  Input: dataset: this will be the input dataset, could be subsets that in leaf nodes
          The dataset is in dimension(..., 8), with the last element the label
  
  Output: S_left, S_left: this seperates the dataset into two parts that will generate the highest information gain
  '''
  # each row in wifis will be a wifi emitter's attribute, [:-1] takes away the label
  wifis = dataset.T[:-1]
  for wifi in wifis:
    print(wifi)

    

In [24]:
find_split(clean_data)

[-64. -68. -63. ... -62. -62. -59.]
[-56. -57. -60. ... -59. -58. -50.]
[-61. -61. -60. ... -46. -52. -45.]
[-66. -65. -67. ... -65. -61. -60.]
[-71. -71. -76. ... -45. -41. -45.]
[-82. -85. -85. ... -87. -90. -88.]
[-81. -85. -84. ... -88. -85. -87.]


In [ ]:
def sort_lits(x):
  