<a href="https://colab.research.google.com/github/shikejianalan/Learning-Note/blob/main/IntroToMLCW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Step 1: Importing data

In [2]:
#  importing data from files

clean_data = np.loadtxt('clean_dataset.txt')
noisy_data = np.loadtxt('noisy_dataset.txt')
print(clean_data.shape)

(2000, 8)


# Step 2: Creating Decision Trees

In [3]:
# this part in the notebook calculates the information gain from entropy and reamainder after made the decision

def gain(s_all,s_left,s_right):
  '''
  This function calculates the information gain
  '''
  return entropy(s_all) - remainder(s_left,s_right) 
  

def entropy(dataset):
  '''
  This function calculates the entropy of the dataset
  '''
  if len(dataset) > 0:
    labels = dataset[:,-1]
    unique, count = np.unique(labels, return_counts=True)
    # print(unique,count)
    p = [number/len(labels) for number in count]
    # print(p)

    result = - np.dot(p,np.log2(p))
    return result


def remainder(s_left, s_right):
  '''
  This function calculate the remainder after made the decision
  '''

  result = entropy(s_left) * len(s_left)/(len(s_left)+len(s_right)) + entropy(s_right) * len(s_right)/(len(s_left)+len(s_right))
  return result

In [4]:
def decision_tree_learning(training_dataset, depth):
  
  pass

In [5]:
def find_split(dataset):
  '''
  This function finds the split that will generate the highest information gain

  Input: dataset: this will be the input dataset, could be subsets that in leaf nodes
          The dataset is in dimension(...,8), with the last row element the label
  
  Output: S_left, S_left: this seperates the dataset into two parts that will generate the highest information gain
  '''
  # each row in wifis will be a wifi emitter's attribute, [:,-1] takes away the label

  highest_gain = -1
  best_cut = None
  best_left = None
  best_right = None


  
  #for each column in the dataset
  for col_num in range(0,len(dataset[0])-1):
    args = np.argsort(dataset[:,col_num])
    sorted_data = dataset[args]

  
    for row_num in range(1,len(dataset)-1):
    # start from the second until the second last, so that left_set and right_set will not be empty
      left_set = sorted_data[:row_num]
      right_set = sorted_data[row_num:]
      IG = gain(dataset, left_set, right_set)
      
      if IG > highest_gain:
        best_cut = (sorted_data[row_num,col_num],col_num)
        best_left = left_set
        best_right = right_set
        highest_gain = IG
  return best_left,best_right,highest_gain,best_cut

  




In [6]:
s_left,s_right,gain,cut = find_split(clean_data)

In [7]:
print(s_left.shape)
print(s_right.shape)
print(gain)
print(cut)
print(s_left)

(1012, 8)
(988, 8)
0.9380693889198293
(-54.0, 0)
[[-74. -62. -66. ... -89. -87.   1.]
 [-73. -62. -66. ... -87. -89.   1.]
 [-73. -61. -65. ... -89. -90.   1.]
 ...
 [-55. -51. -48. ... -82. -86.   4.]
 [-55. -52. -45. ... -87. -85.   4.]
 [-55. -49. -51. ... -84. -88.   4.]]


In [8]:
def split_data(dataset,row_num):
  '''
  This function will sort with respect to the correspond row.
  Input: dataset: shape(6,...) is the transpose of the original dataset
          row_num: the rows you want to sort by
  Output: sorted-data: dim of (8,...)
  '''
  args = dataset[row_num].argsort()
  sorted_data = np.array(dataset[:,args])
  # start from the second until the second last, so that left_set and right_set will not be empty
  for i in range(1,len(sorted_data[row_num])-1):
    left_set = sorted_data[:,i]
    right_set = sorted_data[:,i:]

  return 